### ISSUE TITLE
jupyter labextension install fails

### ISSUE THREAD

**Issue by rsharris** [higlass/scipy19#3]
MacOS 10.14.6

Working with a fresh uninstall/install of anaconda, from Anaconda3-2021.05-MacOSX-x86_64.sh

conda version 4.10.3

cd scipy19
conda env create --file environment.yml  gave no noticeable complaints

conda activate higlass-scipy19
jupyter labextension install @jupyter-widgets/jupyterlab-manager
failed with
	ValueError: "@jupyter-widgets/jupyterlab-manager" is not a valid extension:
	schemaDir is empty: "./schema"

I'm a novice jupyter user, so it's unclear to me where it's looking for that schema subdirectory. There's no such directory in the scipy19 directory.

jupyter labextension install higlass-jupyter@0.2.1
also fails, reporting "RuntimeError: JupyterLab failed to build".
Examining the jupyterlab-debug log file I see a bunch of warnings about "unmet peer dependency"s which I suppose could be the result of of that first labextension failure.

In spite of those failures, I *am* able to start Jupyterlab as described a few lines lower in the readme. But my guess is that things ain't gonna work, so I haven't pursed any of the examples.

**Comment by flekschas** [comment]
This might be a version mismatch. Could you try fixing `higlass-python` to `0.2.1` or `0.3.0` in `environment.yml` as follows?

```yaml
name: higlass-scipy19
channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - python>=3.7
  - nodejs=10.*
  - pip
  - pip:
    - jupyterlab==1.1.1
    - ipywidgets==7.5.1
    - higlass-python==0.2.1
    - nbserverproxy
```

Starting with `higlass-python` version `0.4.0` you should use Jupyterlab v2.
